Remove printf evaluating desc as format string
This breaks setting attributes containing % because:

        > printf "%s %s..." % [ "default", "setting test=something with % in it" ]
        ArgumentError: too few arguments
                from (irb):21:in `printf'
                from (irb):21
                from /usr/bin/irb:12:in `<main>'

Removed this because it's probably cruft.